version: "3"

services:

  scheduler-sdk-extensions-csharp-preview-test:
    build: .
    container_name: scheduler-sdk-extensions-csharp-preview-test
    image: finbourne/scheduler-sdk-extensions-csharp-preview-test
    environment:
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PASSWORD
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_SCHEDULER_API_URL
      - FBN_APP_NAME
    volumes:
      - .:/usr/src